language: node_js
node_js:
 - "node"

services:
  - mysql

before_script:
  - mysql -u root -e "CREATE DATABASE simulados_database;"
  - mysql -u root -e "CREATE USER 'dev'@'localhost' IDENTIFIED BY 'dev';" < test/travis.sql
  - mysql -u root -e "GRANT ALL ON simulados_database.* TO 'dev'@'localhost';"

cache:
  directories:
    - "node_modules"